### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by eranault** [remypereira99/UFC-Web-Scraping#4]
Hey Remy, great project ! 

I was actually running it, and I fell on this error : 

Traceback (most recent call last):
  File "/Users/eranault/Downloads/UFC-Web-Scraping-main/ufc_web_scraper/main.py", line 19, in <module>
    main()
  File "/Users/eranault/Downloads/UFC-Web-Scraping-main/ufc_web_scraper/main.py", line 16, in main
    normalise_tables()
TypeError: 'module' object is not callable

Am I crossing a line if I ask for help ?

Thanks again !

**Comment by robert-todora** [comment]
Hey, I know this was posted almost 2 years ago, but to answer this question, in main.py, you need to comment out the "normalise_tables" import and the line where it calls it because the function name and the name of the file are the same which causes this issue. After the program runs then after you can run `python3 normalise_table.py ` to complete everything: 

Updated main.py:
```

from scraper import get_urls, events, fights, fightstats, fighters#, normalise_table
def main():

    #Scrapes all urls from ufcstats.com
    get_urls.get_event_urls()
    get_urls.get_fight_urls()
    get_urls.get_fighter_urls()

    #Iterates through urls and scrapes key data into csv files
    events.scrape_events()
    fights.scrape_fights()
    fightstats.scrape_fightstats()
    fighters.scrape_fighters()

    #Normalises tables for clean final output
    #normalise_table.normalise_tables()

if __name__ == '__main__':
    main()

```
